#
# makeusers.yml
# -------------
# Create testing users borg, zac, hobo and neeve
#
# usage:
#  ansible-palybook makeusers.yml
#
# author:  Michael Arbet (marbet@redhat.com)
# license: GNU GPL v3
# Copyright (C) 2019 by Michael Arbet
#

---
- hosts: remote
#  become: yes
#  become_user: root
  vars:
    ansible_user: root

  tasks:
    - name: regular user with bash
      user:
        name: borg
        comment: "Bashed Being"
        shell: /bin/bash
        skeleton: /etc/skel

    - name: regular user with zsh
      user:
        name: zac
        comment: "The Zsh Hero"
        shell: /bin/zsh
        skeleton: /etc/skel

    - name: homeless user with bash
      user:
        name: hobo
        comment: "Proudly Homeless"
        shell: /bin/bash
        create_home: false

    - name: disabled user
      user:
        name: neeve
        comment: "Never Log In"
        shell: /bin/nologin
        skeleton: /etc/skel

