#
# shelldebug.yml
# --------------
# add/remove debugging message into shell startup scripts
# one can immediately see what files are executed during startup
# Note: this breaks `scp`! (any output breaks scp)
#
# usage:
#  ansible-palybook shelldebug.yml -e debug=<present|absent>
#
# author:  Michael Arbet (marbet@redhat.com)
# license: GNU GPL v3
# Copyright (C) 2019 by Michael Arbet
#

---
- hosts: local
  vars:
    debugline: "echo STARTUP: {{item}}"
    userfiles:
        - ~/.profile
        - ~/.bashrc
        - ~/.bash_profile
        - ~/.bash_logout
        - ~/.bash_prompt        # crazy hypriotos prompt settings
        - ~/.zshrc
        - ~/.nosuchfile
    rootfiles:
        - /etc/profile
        - /etc/bashrc
        - /etc/nosuchfile

  tasks:
    - name: debug line in system startup files
      become: yes
      become_user: root
      lineinfile:
        path: "{{item}}"
        line: "{{debugline}}"
        state: "{{debug}}"
        create: no
        insertafter: "$" #insert after first line
      loop: "{{rootfiles}}"
      ignore_errors: yes

    - name: debug line in user profile
      lineinfile:
        path: "{{item}}"
        line: "{{debugline}}"
        state: "{{debug}}"
        create: no
        insertafter: "$" #insert after first line
      loop: "{{userfiles}}"
      ignore_errors: yes

